using System.ComponentModel.DataAnnotations;
using System.Reflection;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Bulud.Base.Exporters;

public class PdfExporter : IExporter
{
    public string ContentType => "application/pdf";
    public string FileExtension => ".pdf";

    public bool CanHandle(string acceptHeader)
    {
        return acceptHeader?.Contains(ContentType, StringComparison.OrdinalIgnoreCase) ?? false;
    }

    public byte[] Export<T>(IEnumerable<T> data)
    {
        var model = data.ToList();

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(20);
                page.DefaultTextStyle(x => x.FontSize(8));

                page.Header().Text("بازتا").SemiBold().FontSize(18).FontColor(Colors.Blue.Medium);

                page.Content().Table(table =>
                {
                    if (!model.Any())
                    {
                        table.Cell().Text("No data found.");
                        return;
                    }

                    var props = typeof(T).GetProperties();

                    // Header
                    table.ColumnsDefinition(columns =>
                    {
                        foreach (var _ in props)
                            columns.RelativeColumn();
                    });
                    
                    var headers = GetHeadersFromData<T>();
                    
                    table.Header(header =>
                    {
                        foreach (var headerName in headers)
                            header.Cell().Element(CellStyle).Text(headerName).SemiBold();
                    });
                    

                    // Rows
                    foreach (var item in model)
                    {
                        foreach (var prop in props)
                        {
                            var value = prop.GetValue(item)?.ToString() ?? string.Empty;
                            table.Cell().Element(CellStyle).Text(value);
                        }
                    }

                    IContainer CellStyle(IContainer container) =>
                        container.PaddingVertical(5).PaddingHorizontal(2).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by buludweb.ir • ");
                    x.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm")).FontSize(10).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }
    
    private List<string> GetHeadersFromData<T>()
    {
        var type = typeof(T);
        var props = type.GetProperties();
        var headers = props.Select(p =>
        {
            var displayAttr = p.GetCustomAttribute<DisplayAttribute>();
            return displayAttr?.Name ?? p.Name;
        }).ToList();

        return headers;
    }
}

