<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Bulud.Base</PackageId>
    <Version>2.0.0</Version>
    <Authors>BuludWeb</Authors>
    <Company>BuludWeb</Company>
    <Description>
      Bulud.NET is a utility library for .NET applications that provides:
      - Custom exception handling
      - Global exception middleware with Serilog &amp; Loki integration
      - Extension methods for EF Core, Claims, Collections, and more
      - Base infrastructure for Repository &amp; DbContext
      - Data exporting to CSV and PDF
      - Authorization helpers and JWT utilities
    </Description>
    <PackageTags>bulud net jwt identity logging pdf serilog</PackageTags>
    <RepositoryUrl>https://github.com/shayanblest/Bulud.NET.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/shayanblest/Bulud.NET.git</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Core\Bulud.Core\Bulud.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
  </ItemGroup>

</Project>
